symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600      # Durée en secondes avant l'expiration des liens de réinitialisation de mot de passe
    throttle_limit: 3600  # Durée en secondes qui doit s'écouler avant qu'un utilisateur puisse demander une nouvelle demande de réinitialisation de mot de passe
    enable_garbage_collection: true     # Active le nettoyage des anciennes demandes de réinitialisation de mot de passe dans la base de données